apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-redis-0
  namespace: robot-shop
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: gp2
  resources:
    requests:
      storage: 1Gi


